Feature/101 base reporter
COSSAS/SOARCA pull request #117
Opened 2024-04-04 15:01 UTC by lucamrgs

Moved from other branch, supersedes PR #106

2024-04-04 19:10 UTC, lucamrgs commented
HTTPOauth2 test failed due to 502 bad gateway :/

2024-04-08 13:03 UTC, MaartendeKruijf requested changes

2024-04-08 13:03 UTC, MaartendeKruijf commented on internal/reporter/reporter.go
> +	ReportStep(executionContext execution.Metadata, step cacao.Step, outVars cacao.Variables, err error) error
remove the error return type

2024-04-08 13:03 UTC, MaartendeKruijf commented on internal/reporter/reporter.go
> +	ReportWorkflow(executionContext execution.Metadata, playbook cacao.Playbook) error
Remove the error return type

2024-04-08 13:03 UTC, MaartendeKruijf commented on test/unittest/decomposer/decomposer_test.go
> +	"soarca/test/unittest/mocks/mock_reporter"
Test that the reporter is called

2024-04-08 13:03 UTC, MaartendeKruijf commented on test/unittest/executor/action/action_executor_test.go
> +	"soarca/test/unittest/mocks/mock_reporter"
Test if the reporter is called

2024-04-08 13:03 UTC, MaartendeKruijf commented on test/unittest/mocks/mock_reporter/mock_downstream_reporter.go
> +	return nil
Missing mack implementation like:

```
args := capability.Called(metadata, command, authentication, target, variables)
	return args.Get(0).(cacao.Variables), args.Error(1)
```

2024-04-08 13:03 UTC, MaartendeKruijf commented on test/unittest/mocks/mock_reporter/mock_reporter.go
> +	return nil
Missing mock as well

2024-04-17 12:05 UTC, MaartendeKruijf requested changes
Please rebase and add mock assertions

2024-04-17 12:05 UTC, MaartendeKruijf commented on test/unittest/decomposer/decomposer_test.go
> +	"soarca/test/unittest/mocks/mock_reporter"
Add to every test mock_reporter.assertExpectations

2024-04-17 12:05 UTC, MaartendeKruijf commented on internal/reporter/reporter.go
> +	maxReporters, _ := strconv.Atoi(utils.GetEnv("MAX_REPORTERS", strconv.Itoa(MaxReporters)))
Maybe get this variable on NEW or just inject it?

2024-04-19 09:14 UTC, MaartendeKruijf commented on internal/controller/controller.go
> +	// TODO: Instantiate reporters from config
Remove comment and create issue

2024-04-19 09:19 UTC, MaartendeKruijf commented on internal/decomposer/decomposer.go
> +	metadata := execution.Metadata{
You're creating a metadata object here and only using the ExecutionId just pass that to ReportWorkflow

2024-04-24 18:06 UTC, MaartendeKruijf approved these changes

2024-04-24 18:07 UTC, merged