Add fin-python-library page to docs
COSSAS/SOARCA pull request #127
Opened 2024-04-10 09:49 UTC by xncz8h

closed #126

2024-04-10 09:56 UTC, MaartendeKruijf commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +IExecutor <- MQTTClient
```suggestion
MQTTClient -> IExecutor
```

2024-04-10 10:44 UTC, MaartendeKruijf commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +def capability_pong_callback(command: Command) -> ResultStructure:
Maybe define the variables like finId, capabilityId and use them at the correct places?

2024-04-23 20:45 UTC, RabbITCybErSeC requested changes

2024-04-23 20:45 UTC, RabbITCybErSeC commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +For documentation about the fin protocol we refer the reader to de documention page of [SOARCA](https://cossas.github.io/SOARCA/docs/soarca-extensions/fin-protocol/)
@xncz8h please fix typo: the reader to `the` documentation page. Plus change link name SOARCA to `Fin Protocol`

2024-04-23 20:45 UTC, RabbITCybErSeC commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +To use the SOARCA Fin library use the following command to install the library using pip:
Please change to: To include the SOARCA Fin library, you can use the following command to install it via pip:

2024-04-23 20:45 UTC, RabbITCybErSeC commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +
remove empty line

2024-04-23 20:45 UTC, RabbITCybErSeC commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +For more examples and the source code, we will refer to the Github page of the [project](https://github.com/COSSAS/SOARCA-FIN-python-library).
Change project to `SOARCA-Fin-python-library` in link

2024-04-23 20:45 UTC, RabbITCybErSeC commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +The SoarcaFin creates `MQTTClient`s for each capability registered, plus one for registering, unregistering and controlling the fin.
The SoarcaFin creates `MQTTClient`s for each capability registered, plus one for registering, unregistering and controlling the fin `itself`.

2024-04-23 20:45 UTC, RabbITCybErSeC commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +To register a fin to SOARCA, first create a `SoarcaFin` object and pass the `fin_id` in the constructor.
Are the specific requirements to the `fin_id`? should this be in a certain format? please explain

2024-04-23 20:45 UTC, RabbITCybErSeC commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +An example is given in this project in the file `examples/pong_example.py`
maybe provide a clickable link here

2024-05-22 07:57 UTC, MaartendeKruijf commented on docs/content/en/docs/soarca-extensions/fin-python-library.md
> +
Missing env definitions and that they need to match with SOARCA's configuration

2024-05-23 07:04 UTC, MaartendeKruijf approved these changes

2024-05-28 07:46 UTC, RabbITCybErSeC approved these changes

2024-05-28 07:46 UTC, merged