first cache reporter documentation
COSSAS/SOARCA pull request #135
Opened 2024-04-25 09:45 UTC by lucamrgs

Adding documentation and logic for a caching component. It interfaces execution reporting functions, database, and can serve the reporting API.

2024-04-25 09:46 UTC, lucamrgs commented
We can discuss interfaces and components naming, and functionalities.

2024-05-06 09:29 UTC, MaartendeKruijf requested changes
Looks goed only a few minor changes needed great work! @lucamrgs

2024-05-06 09:29 UTC, MaartendeKruijf commented on test/unittest/reporters/downstream_reporter/cache_test.go
> +	_ = cacheReporter.ReportWorkflowStart(executionId0, playbook)
assert error is nil

2024-05-06 09:29 UTC, MaartendeKruijf commented on test/unittest/reporters/downstream_reporter/cache_test.go
> +	_ = cacheReporter.ReportWorkflowStart(executionId0, playbook)
assert error is nil

2024-05-06 09:29 UTC, MaartendeKruijf commented on test/unittest/reporters/downstream_reporter/cache_test.go
> +	_ = cacheReporter.ReportWorkflowStart(executionId0, playbook)
assert error is nil

2024-05-06 09:29 UTC, MaartendeKruijf commented on test/unittest/reporters/downstream_reporter/cache_test.go
> +func TestReportStepStart(t *testing.T) {
combine in one test

2024-05-06 09:29 UTC, MaartendeKruijf commented on test/unittest/reporters/downstream_reporter/cache_test.go
> +	_ = cacheReporter.ReportWorkflowStart(executionId0, playbook)
assert error

2024-05-06 09:29 UTC, MaartendeKruijf commented on test/unittest/reporters/reporter/reporter_test.go
add a test to assert more then one reporter is called (add two downstream reporter mocks and assert they are called)

2024-05-06 09:29 UTC, MaartendeKruijf commented on test/unittest/reporters/reporter/reporter_test.go
The is more of an addition to this test, we should have done that with the reporter pull request but lets add it now

2024-05-06 11:10 UTC, lucamrgs commented on internal/guid/guid.go
>  type IGuid interface {
I tested again and we don't. It was a left-over of a previous definition of some reporting functions. I will remove it in the next push.

2024-05-06 12:13 UTC, MaartendeKruijf approved these changes

2024-05-06 12:13 UTC, merged