add first reporter api
COSSAS/SOARCA pull request #137
Opened 2024-05-01 09:57 UTC by lucamrgs

Defines the initial API endpoints and route logic for reporting

2024-05-13 15:58 UTC, MaartendeKruijf requested changes
Nice start on the api we need to refine a bit but looks good already

2024-05-13 15:58 UTC, MaartendeKruijf commented on test/unittest/mocks/mock_reporter/mock_downstream_reporter.go
> +}
These should be in a separate mock as they are not in the cache interface

2024-05-13 15:58 UTC, MaartendeKruijf commented on test/unittest/reporters/downstream_reporter/cache_test.go
> +	report "soarca/models/cache"
Here is a mismatch between models and naming

2024-05-13 15:58 UTC, MaartendeKruijf commented on test/integration/api/reporter_api_test.go
Place this in the unittest folder as it's an unittest

2024-05-13 15:58 UTC, MaartendeKruijf commented on docs/content/en/docs/core-components/api-reporter.md
> +| ----------------- | --------------------- | ----------------- | ----------- |
Automated execution field is missing here

2024-05-13 15:58 UTC, MaartendeKruijf commented on docs/content/en/docs/core-components/api-reporter.md
> +|server_side_error| A server-side error occurred. |
I've sugested await_user_input https://github.com/cyentific-rni/workflow-status/pull/3 if that goes true we need to add that here

2024-05-14 08:29 UTC, MaartendeKruijf requested changes

2024-05-14 08:29 UTC, MaartendeKruijf commented on docs/content/en/docs/core-components/api-reporter.md
> +| ----------------- | --------------------- | ----------------- | ----------- |
Also see what other fields would make sense to include

2024-05-14 10:26 UTC, lucamrgs commented on docs/content/en/docs/core-components/api-reporter.md
> +|execution_id       |UUID                   |string             |The id of the execution of the playbook where the step resides
Took me forever but now it's done

2024-05-14 10:49 UTC, lucamrgs commented on routes/reporter/reporter_api.go
> +func SendErrorResponse(g *gin.Context, status int, message string, orginal_call string) {
What do you mean?

2024-05-14 10:58 UTC, lucamrgs commented on routes/reporter/reporter_api.go
> +//	@error			400
You mean @param?

2024-05-14 11:01 UTC, lucamrgs commented on routes/reporter/reporter_api.go
> +//	@error			400
Do you mean the "@ param" comment?

2024-05-15 10:13 UTC, MaartendeKruijf submitted a review, later dismissed

2024-05-15 10:13 UTC, MaartendeKruijf commented on test/unittest/routes/reporter_api/reporter_api_test.go
> +			Status:      2,
Status 2 is an enum right?

2024-05-15 11:02 UTC, MaartendeKruijf approved these changes

2024-05-15 11:02 UTC, merged