Adding mutex locks in cache to prevent race conditions
COSSAS/SOARCA pull request #185
Opened 2024-07-23 15:20 UTC by lucamrgs

2024-07-25 11:59 UTC, lucamrgs commented
@MaartendeKruijf how do we test this?

2024-08-02 09:24 UTC, lucamrgs commented
@MaartendeKruijf is this enough or should we do some more in-depth testing and such?

2024-08-02 09:26 UTC, MaartendeKruijf commented
@lucamrgs let met check

2024-08-02 10:02 UTC, MaartendeKruijf requested changes

2024-08-02 10:02 UTC, MaartendeKruijf commented on internal/reporter/downstream_reporter/cache/cache.go
> +	cacheReporter.mutex.Lock()
I would gaurd the most critical sections in getExecutions and addExecutions. Also then just use a go routine to let the decomposer not wait on any mutex.

2024-08-08 08:38 UTC, lucamrgs commented
@MaartendeKruijf both requested changes are implemented

2024-08-08 13:25 UTC, MaartendeKruijf approved these changes

2024-08-08 13:26 UTC, merged