add waitgroup to reporting calls to ensure consistency
COSSAS/SOARCA pull request #226
Opened 2024-09-27 15:35 UTC by lucamrgs

Added a sync.WaitGroup to the reporter module, which is used to ensure that the routine that reports the workflow end wg.Wait()-s before executing, allowing for all other reporting subroutines to record the progress correctly.

Note: I don't know if this can be unit-tested.

2024-10-02 17:02 UTC, MaartendeKruijf requested changes
I think we should solve this with an interface change which allows for the calling time to be added to the reporting time. So even when reporting would take 10 seconds the original time is used. If an endstep report fails we remain with the wait group with the proposed change

2024-10-15 08:40 UTC, lucamrgs commented
Why is sigrid bullying me tho

2024-10-23 12:13 UTC, MaartendeKruijf requested changes

2024-10-23 12:13 UTC, MaartendeKruijf commented on internal/executors/action/action.go
> +		executor.reporter.ReportStepEnd(meta.ExecutionId, metadata.Step, cacao.NewVariables(), err, executor.time.Now())
Try to use `defer` it might be that you need to move up the creation of the `returnVariables`

2024-10-23 12:13 UTC, MaartendeKruijf commented on test/unittest/reporters/downstream_reporter/cache_test.go
> -func TestInvalidStepReportAfterExecutionEnd(t *testing.T) {
Please add the regression case for reporting a step after workflow end

2024-11-01 13:18 UTC, lucamrgs commented on internal/executors/action/action.go
> +	defer func() {
Note defer changes

2024-11-01 13:18 UTC, lucamrgs commented on internal/executors/playbook_action/playbook_action.go
> +	defer func() {
Note defer changes

2024-11-07 15:34 UTC, merged