refactor on api structure start
COSSAS/SOARCA pull request #269
Opened 2024-12-03 12:59 UTC by RabbITCybErSeC

2024-12-05 09:41 UTC, lucamrgs approved these changes
Looks nice and uniform to me!

2024-12-05 15:34 UTC, MaartendeKruijf requested changes
Nice job!

2024-12-05 15:34 UTC, MaartendeKruijf commented on pkg/api/playbook/playbook_api.go
> +// newplaybookcontroller makes a new instance of playbookcontroler
Update description to match capitalisation of function. Maybe even be more descriptive.

2024-12-05 15:34 UTC, MaartendeKruijf commented on pkg/api/playbook/playbook_api.go
> +// a playbookhandler implements the playbook api endpoints is dependent on a database.
Capitalise correctly

2024-12-05 15:34 UTC, MaartendeKruijf commented on pkg/api/playbook/playbook_api.go
>  // getAllPlaybooks GET handler for obtaining all the playbooks in the database and return this to the gin context in json format
Fix

2024-12-05 15:34 UTC, MaartendeKruijf commented on pkg/api/playbook/playbook_api.go
Fix capitalisation for all descriptions in file

2024-12-05 15:34 UTC, MaartendeKruijf commented on pkg/api/playbook/playbook_api.go
> +func (playbookHndlr *playbookHandler) GetAllPlaybooks(g *gin.Context) {
```suggestion
func (handler *playbookHandler) GetAllPlaybooks(g *gin.Context) {
```

2024-12-05 15:34 UTC, MaartendeKruijf commented on pkg/api/reporter/reporter_api.go
Fix description capitalisation

2024-12-06 08:53 UTC, MaartendeKruijf approved these changes

2024-12-06 08:53 UTC, merged