Feature/272 manual step api implementation
COSSAS/SOARCA pull request #275
Opened 2024-12-04 15:53 UTC by lucamrgs

2024-12-04 16:11 UTC, lucamrgs commented
Documentation needs to be adapted to these changes

2024-12-20 11:16 UTC, lucamrgs commented
Thanks @MaartendeKruijf for rebasing in the middle of my edits on the draft pull request

2024-12-20 16:00 UTC, lucamrgs commented
I think we need to fix a couple things trough the way that out args would be passed down to the manual command capability

2025-01-16 14:30 UTC, MaartendeKruijf commented on pkg/models/manual/manual.go
> +// Object stored in interaction storage and provided back from the API
Move the api models to the api folder

2025-01-16 14:50 UTC, MaartendeKruijf requested changes

2025-01-16 14:50 UTC, MaartendeKruijf commented on docs/content/en/docs/core-components/modules.md
> +interaction --> manual : capabilityChannel <- InteractionResponse
Merge intergration and interaction channel into one

2025-02-14 13:31 UTC, lucamrgs commented
@MaartendeKruijf what changes did you request? Not sure I see them

2025-02-17 09:13 UTC, lucamrgs commented on pkg/models/cacao/cacao.go
> +	Name        string `bson:"name,omitempty" json:"name,omitempty" example:"__example_string__"`        // The name of the variable in the style __variable_name__ (included in object for utility)
To clarify that we have it there for utility purpose, and it's not actual part of the CACAO spec. If you think it's not needed though I can remove it

2025-02-17 09:20 UTC, lucamrgs commented on pkg/models/cacao/cacao.go
> +type OutArgs []string
Nope. I removed it.

2025-02-26 12:42 UTC, MaartendeKruijf requested changes
I've finally looked at the PR in depth some final changes and then we can merge 🎉  note we need to merge #325  first to get rid of the capability controller movement

2025-02-26 12:42 UTC, MaartendeKruijf commented on pkg/core/capability/fin/controller/controller.go
PR #325 needs to be merged first

2025-02-26 12:42 UTC, MaartendeKruijf commented on pkg/api/manual/manual_api.go
> +			ok = false
Directly return if some variable is not oke

2025-02-26 12:42 UTC, MaartendeKruijf commented on pkg/api/manual/manual_api.go
> +// Utility
Add test for the utility functions from the manual folder

2025-02-26 12:42 UTC, MaartendeKruijf commented on pkg/api/manual/manual_api.go
> +func (manualHandler *ManualHandler) PostContinue(g *gin.Context) {
This function is a bit long we should refactor it

2025-03-03 13:14 UTC, MaartendeKruijf submitted a review, later dismissed
Nice work!

2025-03-03 13:41 UTC, MaartendeKruijf approved these changes

2025-03-03 13:43 UTC, merged